#!/bin/bash
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"
OLDGW=10.209.79.254

if [ ! -e /tmp/pptp_oldgw ]; then
    echo "" > /tmp/pptp_oldgw
fi

dscacheutil -flushcache
source /etc/ppp/chnroutes-up

# 根据指定wifi，添加特定路由。适用于渣浪这种，很多内网ip的情况,有需要自己打开下面注释，根据自己情况修改sina-up
# currentwifi=Current Wi-Fi Network: sina-web
# if [[  !=  ]]
# then
#     source /etc/ppp/sina-up
# fi
